baseurl = "https://akshaysasidharan.dev"
languageCode = "en-us"
theme = "hello-friend-ng"
DefaultContentLanguage = "en"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "Monday, Jan 2, 2006"

  # Metadata mostly used in document's head
  description = "Technology blog by Akshay Sasidharan"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  homeSubtitle = "Software Engineer"
  customCSS = ["css/custom.css"]

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/akshaysasidrn"

  [[params.social]]
    name = "email"
    url  = "mailto:akshaysasidharan93@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/aksh93"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/akshay-sasidharan/"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/akshaysasidharan/"

[languages]
  [languages.en]
    title = "Akshay Sasidharan"
    subtitle = "Exploring computer wizadry"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
